### ISSUE TITLE
obj.rs example panics

### ISSUE THREAD

**Issue by WarmongeringBeaver** [sebcrozet/kiss3d#226]
### How to reproduce

Running `cargo run --example obj` results in panic:
```Rust
kiss3d on master ❯ RUST_BACKTRACE=full cargo run --example obj

<warnings>

    Finished dev [unoptimized + debuginfo] target(s) in <time>s
     Running `target/debug/examples/obj`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/scene/scene_node.rs:865:9
```
<details>
<summary>Full backtrace</summary>

```Rust
stack backtrace:
   0:     0x5594387a4114 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x5594387a4114 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x5594387a4114 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5594387a4114 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5594387c63fc - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:     0x5594387a11e3 - std::io::Write::write_fmt::h893169117de3cc15
                               at src/libstd/io/mod.rs:1426
   6:     0x5594387a6925 - std::sys_common::backtrace::_print::h8ab61d4120f7a335
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5594387a6925 - std::sys_common::backtrace::print::h8aae19fbb153bf2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5594387a6925 - std::panicking::default_hook::{{closure}}::h1ee5b7d8b6f83429
                               at src/libstd/panicking.rs:204
   9:     0x5594387a6672 - std::panicking::default_hook::hd6c32c13403f9210
                               at src/libstd/panicking.rs:224
  10:     0x5594387a6f82 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
                               at src/libstd/panicking.rs:470
  11:     0x5594387a6b6b - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x5594387c4451 - core::panicking::panic_fmt::h2c05f81b567d1861
                               at src/libcore/panicking.rs:85
  13:     0x5594387c4273 - core::option::expect_none_failed::ha9782a6ef355446f
                               at src/libcore/option.rs:1211
  14:     0x5594380cdf8a - core::result::Result<T,E>::unwrap::hcaae4886674e1a44
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/result.rs:1003
  15:     0x55943809e6a3 - kiss3d::scene::scene_node::SceneNode::add_obj::hdb11ee25db676d78
                               at src/scene/scene_node.rs:865
  16:     0x55943809e800 - kiss3d::window::window::Window::add_obj::h823faa0e06d570ce
                               at src/window/window.rs:257
  17:     0x5594380928cd - obj::main::h4bcd0600712bc870
                               at examples/obj.rs:16
  18:     0x5594380925ab - std::rt::lang_start::{{closure}}::hbcafedf607bf53a1
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  19:     0x5594387a6a43 - std::rt::lang_start_internal::{{closure}}::h9a4aa16acf1cdc99
                               at src/libstd/rt.rs:52
  20:     0x5594387a6a43 - std::panicking::try::do_call::h0b6fc9f6090c1e2b
                               at src/libstd/panicking.rs:303
  21:     0x5594387aadb7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  22:     0x5594387a756c - std::panicking::try::h9eaeeaa81242ec77
                               at src/libstd/panicking.rs:281
  23:     0x5594387a756c - std::panic::catch_unwind::h07d504c1b691e8fb
                               at src/libstd/panic.rs:394
  24:     0x5594387a756c - std::rt::lang_start_internal::hcea4e704875ab132
                               at src/libstd/rt.rs:51
  25:     0x559438092587 - std::rt::lang_start::h7f4990c18daf0ea5
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  26:     0x559438092c6a - main
  27:     0x7f97af2d80b3 - __libc_start_main
  28:     0x55943809119e - _start
  29:                0x0 - <unknown>
```
</details>

### Meta
```
❯ bat Cargo.toml | rg version -m 1 ; rustc --version ; cargo --version ; uname -srvpio
version = "0.24.1"
rustc 1.43.1 (8d69840ab 2020-05-04)
cargo 1.43.0 (2cbe9048e 2020-05-03)
Linux 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 GNU/Linux
```
(same behavior on `cargo 1.45.0-nightly (f534844c2 2020-05-06)`)

**Comment by sebcrozet** [comment]
Hi! This is because this example needs to be run on he `examples` sub-directory (`cd examples; cargo run --example obj`) because it needs to find the obj file there.

**Comment by alvinhochun** [comment]
A possible fix would be to include the absolute path at compile time with `env!("CARGO_MANIFEST_DIR")`.

Also weird that the `obj` example expects current dir to be in `examples/` but the `ui` example expects the manifest dir. I wonder if there are other examples relying on relative paths.
