### ISSUE TITLE
draw_lines example error on Mac OS

### ISSUE THREAD

**Issue by dsillman2000** [sebcrozet/kiss3d#318]
I'm experiencing the same error.
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1281`,
 right: `0`', /Users/dsillman/.cargo/registry/src/github.com-1ecc6299db9ec823/kiss3d-0.35.0/src/renderer/line_renderer.rs:89:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:203:5
   4: <kiss3d::renderer::line_renderer::LineRenderer as kiss3d::renderer::renderer::Renderer>::render
             at /Users/dsillman/.cargo/registry/src/github.com-1ecc6299db9ec823/kiss3d-0.35.0/src/renderer/line_renderer.rs:89:9
   5: kiss3d::window::window::Window::render_scene
             at /Users/dsillman/.cargo/registry/src/github.com-1ecc6299db9ec823/kiss3d-0.35.0/src/window/window.rs:1183:9
   6: kiss3d::window::window::Window::render_single_frame
             at /Users/dsillman/.cargo/registry/src/github.com-1ecc6299db9ec823/kiss3d-0.35.0/src/window/window.rs:1114:13
   7: kiss3d::window::window::Window::do_render_with
             at /Users/dsillman/.cargo/registry/src/github.com-1ecc6299db9ec823/kiss3d-0.35.0/src/window/window.rs:1074:29
   8: kiss3d::window::window::Window::render_with
             at /Users/dsillman/.cargo/registry/src/github.com-1ecc6299db9ec823/kiss3d-0.35.0/src/window/window.rs:1044:9
   9: kiss3d::window::window::Window::render
             at /Users/dsillman/.cargo/registry/src/github.com-1ecc6299db9ec823/kiss3d-0.35.0/src/window/window.rs:977:9
  10: shape_log_viewer::main
             at ./src/main.rs:13:11
  11: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I'm using version 0.35.0 of kiss3d. I'm using rustc 1.66.1. I'm on Mac OS Monterey 12.6.1 (apple M1 chip, Macbook Pro 2022). Any idea what might be causing this @donkeyteethUX ?

_Originally posted by @dsillman2000 in https://github.com/sebcrozet/kiss3d/issues/307#issuecomment-1413037427_

**Comment by jamwaffles** [comment]
Using the latest release (0.35) on macOS I can reproduce this error. It is caused by something in `kiss3d` when calling `window.set_line_width`. If you don't call this method, everything works (for me at least). Because I'm not relying on the lines being super visible, I just turn off calls to `set_lines_width` when under macOS:

```rust
#[cfg(not(target_os = "macos"))]
window.set_line_width(1.0);
```

This is also relevant to specific objects, e.g.

```rust
let ball = ncollide3d::procedural::sphere(2.0, 20, 20, false);
let mut ball = window.add_trimesh(ball, Vector3::from_element(1.0));
ball.set_color(0.7, 0.7, 0.7);

#[cfg(not(target_os = "macos"))]
ball.set_lines_width(1.0);
```
