### ISSUE TITLE
Kiss3d failing under Wayland

### ISSUE THREAD

**Issue by pgdooley** [sebcrozet/kiss3d#331]
I have a Rust program (an n-body simulator) that uses Kiss3d.  Everything works fine under X11 but under Wayland my program exits immediately with the following error:

interface 'wl_surface' has no event 2
thread 'main' panicked at /home/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kiss3d-0.35.0/src/window/gl_canvas.rs:80:14:
called `Result::unwrap()` on an `Err` value: OsError("eglInitialize failed")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: queue 0x6477305b90f0 destroyed while proxies still attached:
  wl_buffer@40 still attached
  wl_buffer@39 still attached
  wl_buffer@38 still attached
  wl_buffer@37 still attached
  wl_buffer@36 still attached
  wl_subsurface@30 still attached
  wl_surface@29 still attached
  wl_subsurface@28 still attached
  wl_surface@27 still attached
  wl_subsurface@26 still attached
  wl_surface@25 still attached
  wl_subsurface@24 still attached
  wl_surface@23 still attached
  wl_subsurface@22 still attached
  wl_surface@21 still attached
  xdg_wm_base@18 still attached
  wl_surface@17 still attached
  zwp_text_input_manager_v3@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zwp_relative_pointer_manager_v1@9 still attached
  wl_seat@8 still attached
  wl_subcompositor@7 still attached
  wl_output@6 still attached
  wl_shm@5 still attached
  wl_compositor@4 still attached

I am running Ubuntu 24.04 and have tried the code out on a variety of different systems.  Any ideas appreciated...

**Comment by pgdooley** [comment]
Running with RUST_BACKTRACE=1 gives:

interface 'wl_surface' has no event 2
thread 'main' panicked at /home/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kiss3d-0.35.0/src/window/gl_canvas.rs:80:14:
called `Result::unwrap()` on an `Err` value: OsError("eglInitialize failed")
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /build/rustc-Px5Ywq/rustc-1.75.0+dfsg0ubuntu1/library/core/src/result.rs:1653:5
   3: <kiss3d::window::gl_canvas::GLCanvas as kiss3d::window::canvas::AbstractCanvas>::open
   4: kiss3d::window::window::Window::do_new
   5: kiss3d::window::window::Window::new_hidden
   6: <plansim::system::SolarSystem as core::default::Default>::default
   7: plansim::main

**Comment by modusmogulus** [comment]
I'm encountering the same error
